#!/bin/sh
set -e

case "$1" in
    configure)
		if which pip3 >/dev/null 2>&1
		then
			pip3 install -U psutil || true
		fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac